create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null,
  role text not null default 'atfal' check (role in ('atfal','admin','super_admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null, body text not null, created_at timestamptz not null default now()
);
create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  title text not null, description text, program_date date, start_time time, created_at timestamptz not null default now()
);
create table if not exists public.namaz (
  id bigint generated by default as identity primary key,
  title text not null, namaz_date date not null, notes text, created_at timestamptz not null default now()
);
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  message text not null, created_at timestamptz not null default now()
);
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null, image_url text not null, created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
alter table public.announcements enable row level security;
alter table public.programs enable row level security;
alter table public.namaz enable row level security;
alter table public.feedback enable row level security;
alter table public.gallery enable row level security;
create policy "profiles own read" on public.profiles for select to authenticated using (id=auth.uid());
create policy "public announcements" on public.announcements for select to authenticated using (true);
create policy "public programs" on public.programs for select to authenticated using (true);
create policy "public namaz" on public.namaz for select to authenticated using (true);
create policy "feedback own insert" on public.feedback for insert to authenticated with check (user_id=auth.uid());
create policy "gallery authenticated" on public.gallery for select to authenticated using (true);
