import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import{createClient}from"@supabase/supabase-js";import"./style.css";
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=createClient(url,key);
function App(){const[s,setS]=useState(null),[username,setU]=useState(""),[password,setP]=useState(""),[tab,setTab]=useState("Home"),[msg,setMsg]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>setS(data.session));const{data}=supabase.auth.onAuthStateChange((_e,x)=>setS(x));return()=>data.subscription.unsubscribe()},[]);
async function login(e){e.preventDefault();setMsg("");const email=username.trim().toLowerCase()+"@atfalbbanggerik.app";const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else setS(data.session)}
if(!s)return <main className="login"><section><h1>Majlis Atfal-ul-Ahmadiyya</h1><h2>B.B. Anggerik</h2><p>Atfal Member Portal</p><form onSubmit={login}><input placeholder="Username" value={username} onChange={e=>setU(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setP(e.target.value)} required/><button>Sign in</button></form>{msg&&<small>{msg}</small>}</section></main>;
return <div className="app"><header><b>Atfal B.B. Anggerik</b><button onClick={()=>supabase.auth.signOut()}>Sign out</button></header><nav>{["Home","Namaz","Programs","Announcements","Feedback","History","Gallery","Profile"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><main><h1>{tab}</h1><p>{tab==="Home"?"Welcome to your Atfal portal.":tab==="History"?"History of Majlis Atfal-ul-Ahmadiyya B.B. Anggerik will appear here.":"This section is connected to Supabase and ready for its data."}</p>{tab==="Feedback"&&<Feedback/>}</main></div>}
function Feedback(){const[m,setM]=useState(""),[ok,setOk]=useState("");async function send(){const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from("feedback").insert({user_id:user.id,message:m});setOk(error?error.message:"Feedback submitted.");if(!error)setM("")}return <div><textarea value={m} onChange={e=>setM(e.target.value)} placeholder="Your feedback"/><br/><button onClick={send}>Submit feedback</button><p>{ok}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);